server:
  port: 8081
spring:
  application:
    name: employee-employee

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5060/eureka, http://localhost:5061/eureka
allowed:
  origin: http://localhost:9527